// AUTO-GENERATED by scripts/build-manifest.mjs — do not edit by hand.
// Re-run: npm run build:manifest (any time sprites change)
export const Sprites = {
  characters: {
    'critic-1': {
      idle: {
        back: '/sprites/characters/critic-1/idle/back.png',
        front: '/sprites/characters/critic-1/idle/front.png',
        left: '/sprites/characters/critic-1/idle/left.png',
        right: '/sprites/characters/critic-1/idle/right.png',
      },
      walk: {
        back: '/sprites/characters/critic-1/walk/back.png',
        front: '/sprites/characters/critic-1/walk/front.png',
        left: '/sprites/characters/critic-1/walk/left.png',
        right: '/sprites/characters/critic-1/walk/right.png',
      },
    },
  },
  ghosts: {},
  stands: {},
  props: {},
} as const;
