// AUTO-GENERATED by scripts/build-manifest.mjs — do not edit by hand.
// Re-run: npm run build:manifest (any time sprites change)
export const Sprites = {
  characters: {},
  ghosts: {},
  stands: {},
  props: {},
} as const;
